

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Providers from "@/app/providers";
import ThemeInitializer from "@/app/ThemeInitializer";
import { GlobalProvider } from "@/context/GlobalContext";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <GlobalProvider>
        <body className="min-h-full flex flex-col">
          <Providers>
            <ThemeInitializer />
            <Navbar />
            {children}
          </Providers>
        </body>
      </GlobalProvider>
    </html>
  );
}

